### ISSUE TITLE
Failed to execute video-transcode function

### ISSUE THREAD

**Issue by rei-smz** [hpcclab/OaaS#158]
Hi.

I updated my OaaS deployment with the latest images, and it failed to execute the video-transcode function in the example.

Here is the error in the logs:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55dd099f2e00] moov atom not found
in-9ec0f93e-be10-4556-af45-c47cd7e2d68c.mp4: Invalid data found when processing input
```
This error never appeared before I updated my deployment.

**Comment by pawissanutt** [comment]
Hi,
It seems like the FFmpeg error. 
Did you make sure that your video is okay?
Also, Was this invocation shown as a success or a failure? Sometimes, it could be a harmless error, but I am unsure.
I just tested it on my setup, and it works fine.
